"""add language to posts

Revision ID: 52477593c23a
Revises: c49c40213fea
Create Date: 2025-03-07 16:29:42.129232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52477593c23a'
down_revision = 'c49c40213fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
